### ISSUE TITLE
Developers seems encode the full file path into the .jar file. 

### ISSUE THREAD

**Issue by limerick1718** [masud-technope/NLP2API-Replication-Package#1]
> java -jar nlp2api-runner-1.0.0.jar -K 10 -task reformulate -query How do I send an HTML email?
> java.io.IOException: Cannot run program "C:\Users\MasudRahman\Anaconda3\envs\python-module\python" (in directory "."): CreateProcess error=2, 系统找不到指定的文件。
>         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
>         at java.lang.Runtime.exec(Runtime.java:620)
>         at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)
>         at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279)
>         at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:336)
>         at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
>         at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
>         at w2vec.python.W2VecCollector.executePythonScript(W2VecCollector.java:37)
>         at w2vec.python.W2VecCollector.getWordVectors(W2VecCollector.java:46)
>         at w2vec.python.WordEmbeddingCollector.getMasterEmbeddingList(WordEmbeddingCollector.java:46)
>         at code.search.bda.scorecalc.APIKeywordProximityCalc.calculateQAProximityLocal(APIKeywordProximityCalc.java:59)
>         at code.search.bda.scorecalc.CodeSearchBDAReformulator.provideRelevantAPIs(CodeSearchBDAReformulator.java:161)
>         at core.runner.NLP2APIRunner.main(NLP2APIRunner.java:97)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
> Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
>         at java.lang.ProcessImpl.create(Native Method)
>         at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
>         at java.lang.ProcessImpl.start(ProcessImpl.java:137)
>         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
>         ... 17 more

It seems that the developer ecode the full file path in the .jar file. Please remove that and do not hard coded. Thx

**Comment by limerick1718** [comment]
Sorry, I check the wrong version in google drive. Please ignore my issue. Thx

**Comment by masud-technope** [comment]
Hope you were able to fix it. Please note that you need to get the big files from Google drive as well :)
